# docker-compose -p mysql-performance-optimization up -d

version: '3.8'
services:
  mysql-1:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 1234